services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "pip install fastapi uvicorn[standard] segno httpx && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
